### ISSUE TITLE
Is it possible to select and copy?

### ISSUE THREAD

**Issue by ifduyue** [tbjgolden/simple-json-viewer#1]
Hello,

Good project. Is it possible to do selection?

**Comment by ifduyue** [comment]
```css
   .json-viewer {
        user-select: auto !important;
    }
```
